### ISSUE TITLE
 No such file or directory: '/lambda_stor/homes/pvasanthakumari/HiDRA/csa_data/raw_data/y_data/response.tsv'

### ISSUE THREAD

**Issue by priyanka9991** [JDACS4C-IMPROVE/HiDRA#8]
<img width="1046" alt="Screen Shot 2023-11-04 at 11 48 47 AM" src="https://github.com/JDACS4C-IMPROVE/HiDRA/assets/86702829/20a54c74-7fae-410a-ab62-24b3df80bf24">

**Comment by jamieOverbeek** [comment]
I have resolved this by adding improve_utils.py and changing data to the csa_data directory
