### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'my_data_dir/rsp_CCLE_split0_train.csv'

### ISSUE THREAD

**Issue by priyanka9991** [JDACS4C-IMPROVE/HiDRA#9]
<img width="904" alt="Screen Shot 2023-11-06 at 3 37 50 PM" src="https://github.com/JDACS4C-IMPROVE/HiDRA/assets/86702829/ef035671-a946-48d7-8082-8e867f00f208">

**Comment by jamieOverbeek** [comment]
csa_feature_gen.py now creates the CANDLE_DATA_DIR if it does not exist.
